import LoanSearchComponent from '@/components/container/LoanSearchComponent'

export default function ClientPage() {
  return (
    <LoanSearchComponent
      slug="iban"
      textcontent={`IBAN: Paranın Dijital Kimliği ve Modern Bankacılığın Sessiz Devrimi  

Evet, o uzun, karışık harf ve rakam dizisi. Cüzdanımızın en arka köşesinde bir yerlere not ettiğimiz, para gönderirken bir harfini yanlış yazmaktan deli gibi korktuğumuz şey. IBAN. Aslında onun ne kadar müthiş bir şey olduğunu hiç düşünmüyoruz bile. Oysa ki o, paranın dijital dünyadaki pasaportu, evrensel kimlik kartı. Paranın uluslararası dolaşımını sağlayan, her şeyi standartlaştıran ve inanılmaz kolaylaştıran bir sistem bu. Düşünsenize, birkaç tıkla, oturduğunuz yerden, dünyanın öbür ucundaki birine saniyeler içinde para ulaştırabiliyorsunuz. İşte bu lüksü bize sunan şey, o ufacık ama devasa öneme sahip IBAN numarasından başka bir şey değil.

Doğuş hikayesi de aslında tam bir kaostan çıkış öyküsü. 90'lı yılların ortaları falan, Avrupa'da bankacılık işlemleri allak bullak durumdaydı. Her ülkenin kendine has, birbirinden farklı ve uyumsuz hesap numarası sistemleri vardı. Para göndermek mi istiyorsun? Hadi bakalım, karşına koskocaman bir form çıkardılar, sayfalarca bilgi doldurmak, saatlerce banka kuyruklarında beklemek zorundaydın insanlar. Ve tabii hata yapma ihtimali de çok yüksekti, paran bir yerlerde kaynayıp gidebilirdi. İşte bu karmaşaya bir son vermek için Avrupa Ödeme Konseyi devreye girdi ve 1997'de bu standart doğdu. Türkiye ise bu partiye biraz daha geç katıldı, tam tarih vermek gerekirse 1 Eylül 2005'te resmen geçiş yapıldı ama asıl zorunlu uygulama 2009'u buldu. O günleri hatırlıyorum da, herkes bankalara koşmuş, yeni hesap numaralarını öğrenmeye çalışıyordu, kafalar epey karışıktı. "TR" ile başlayan bu yeni numaralar hepimiz için garip gelmişti ilk başta.

Yapısına gelirsek, aslında o kadar rastgele bir sürü harf ve rakam değil, her birinin bir anlamı var. Mesela bizim ülkemizdeki IBAN'lar 26 haneden oluşuyor. İlk iki karakter her zaman TR, yani bizi temsil eden ülke kodu. Hemen peşinden gelen iki rakam, kontrol numarası olarak geçiyor, işte transferlerde hatayı önleyen asıl kahramanlar onlar. Sonra beş rakam gelir, o da bankanın kendi numarasıdır. Mesela hangi banka olduğu oradan belli olur. Bir hanelik rezerv alanı derler, o da gelecek için ayrılmış boşluk. Ve en sonda da zaten bildiğimiz 16 hanelik esas hesap numaramız yer alıyor. Bu standardizasyon o kadar başarılı oldu ki, bugün dünyada yetmişi aşkın ülke bu sistemi kullanıyor. Ve istatistiklere göre, IBAN'ın hayatımıza girmesiyle birlikte bankalar arası para transferlerinde yaşanan hatalar inanılmaz bir şekilde, neredeyse %99 oranında azaldı. Eskiden yanlış hesaba para gönderdiğinde, o parayı geri almak için dağlar kadar evrak imzalamak, haftalar belki aylarca beklemek gerekirdi. Şimdi öyle mi? Sistem zaten sen hatalı bir IBAN yazmaya kalktığında anında uyarıyor, "Bu IBAN doğru değil" diyor. Çok büyük bir stres yükünü sırtımızdan aldığını söylesek yanlış olmaz.

Kişisel bir şeyler de söyleyeyim ben bu konuda. Geçen sene, freelance bir iş yapmıştım, müşterim de İspanya'daydı. Ödemeyi alacağım zaman, eskiden olsa, gidip bankada kuyruk bekleyeceğim, dolar ya da euro cinsinden havale formu dolduracaktım, komisyonlar da ne kadar keser bilmem kaç günde hesabıma geçer derdim. Ama öyle olmadı. Sadece bana IBAN'ını ver dedim, verdi. İnternet bankacılığına girdim, ilgili bölüme IBAN'ı yapıştırdım, adını falan yazdım, üç dakika sonra işlem tamamdı. Komisyonu da gayet makuldu hem. Bu arada, bu gibi işlemlerde farklı bankaların komisyon oranları inanılmaz değişkenlik gösteriyor, onu da fark ettim. Mesela ihtiyackredisi.com gibi sitelerde bu oranları karşılaştırmak mümkün, cidden işe yarıyor, bakın söylemeden geçmeyeyim.

Bir de tabii otomatik ödeme meselesi var. IBAN'ın hayatımıza kattığı en büyük nimetlerden biri. Artık neredeyse her şey otomatik. Kira, elektrik faturası, su faturası, doğalgaz, internet, telefon, kredi kartı borcu… Hepsi biz hiç farkında olmadan, bizim için ayın belli günlerinde ödeniyor. Hayatı inanılmaz kolaylaştırdı. Ama burada küçük bir uyarı da yapmak lazım, bu rahatlığa aldanıp da hiç takip etmemek olmaz. Ayda bir mutlaka, ama mutlaka hesap hareketlerinize göz atın. Bir arkadaşımın başına geldi, aynı fatura iki kere çekilmiş hesabından, adamlar iki ay boyunca aynı parayı ikişer kere almışlar, ancak üçüncü ay fark etti. Sonra uğraş uğraş bitmedi. O yüzden dikkat.

Uluslararası para transferi yaparken de dikkat edilecek birkaç ince nokta var tabii. Bir kere, IBAN doğrulaması yapmak şart. Neredeyse tüm bankaların internet sitelerinde ya da mobil uygulamalarında IBAN doğrulama araçları var, onu kullanın. Sadece IBAN yetmez, alıcı adını da tam ve doğru bir şekilde yazmak gerekiyor. Bazı ülkelerde Swift kodu diye bir şey de isteyebiliyorlar, onu da sormak lazım. Bir de döviz cinsini netleştirmekte fayda var, hangi para birimiyle gönderdiğiniz önemli.

Ticaret tarafında ise durum daha da etkileyici. Artık küçücük bir girişimci, ihracat yapmak istediğinde, müşterisinden kolayca ödeme alabiliyor IBAN sayesinde. 2022'deki bir veriye göre, Türkiye'ye giren dövizlerin %68'i doğrudan IBAN üzerinden yapılan transferlerle geliyormuş. Bu da demek oluyor ki, sistem hem yaygın hem de son derece güvenilir.

Tabii her güzel şeyin bir kötü tarafı da var ne yazık ki. Son dönemlerde "IBAN dolandırıcılığı" diye bir şey türedi. Sahte faturalar gönderip, insanları kandırıp, paralarını alıyorlar. O yüzden aman dikkat diyorum. Tanımadığınız kişilere asla ve asla IBAN'ınızı vermeyin. Size ödeme talep eden e-postalar geldiğinde, mutlaka kaynağını doğrulayın. Ve banka hesap bilgilerinizi, IBAN'ınızı sosyal medyada paylaşmak falan? Sakın yapmayın, asla!

Şu dijital çağda, IBAN adeta ev adresimiz gibi oldu artık. Nasıl ki fiziksel ev adresimizi herkese vermiyor, onu koruyorsak, IBAN'ımızı da aynı şekilde korumamız gerekiyor. Bu güvenlik konularında ihtiyackredisi.com'un hazırladığı rehberler gerçekten faydalı olabiliyor, online işlem yaparken nasıl önlem alınır, neye dikkat edilir, hepsini anlatıyorlar.

İlginç bir bilgi daha, IBAN aslında durağan bir sistem de değil, sürekli gelişiyor. 2024 itibariyle bazı ülkeler, IBAN'ların yanına QR kod entegre etmeye bile başladılar. Yakın gelecekte belki de hesap numaralarımızı birine söylemeyeceğiz, sadece telefonumuzu uzatıp QR kodunu okutacağız ve para anında transfer olacak. Teknoloji inanılmaz hızlı ilerliyor ve IBAN da bu akışa ayak uyduruyor.

Son sözüm şu olabilir; IBAN, modern ekonominin, dijital dünyanın görünmez işçilerinden biri. Farkında olmasak da, arka planda sessiz sedasız çalışıp, global ticaretin bu kadar hızlı dönmesini sağlayan ana dişlilerden. Eğer siz de farklı bankaların IBAN'lı işlemlerde, özellikle de yurtdışı transferlerde ne kadar komisyon kestiğini merak ediyorsanız, ihtiyackredisi.com gibi platformlara bir göz atmanızı tavsiye ederim. Unutmayın, paranızı doğru yönetmenin ilk adımı, bilinçli bir tüketici olmaktan geçiyor.

Not: Bu yazıyı okurken, cebinizdeki, cüzdanınızdaki kağıt paranın aslında toplam paranızın çok küçük bir kısmı olduğunu, paranın %90'dan fazlasının dijital bir veri, bir kayıt olduğunu hatırlatmak isterim. IBAN'lar da işte bu dijital ekonominin, bu kayıt sisteminin en kritik araçlarından biri. Öyle ki, artık dünyanın bazı yerlerinde, IBAN kullanarak doğrudan kripto para bile alınabiliyor, sistem o kadar esniyor. Düşünün artık.`}
    />
  )
}
