export const blog_burgan_bank = {
  slug: 'burgan-bank',
  meta: {
    title: 'Burgan Bank 2025: En Güncel Faiz Oranları, Kredi Ürünleri ve Dijital Bankacılık Rehberi',
    description: '2025 yılında Burgan Bank tüm ürünleri detaylı inceleme: Mevduat faiz oranları, kredi seçenekleri, kredi kartı avantajları, dijital bankacılık özellikleri ve uzman yorumlarıyla kapsamlı rehber.',
    keywords: [
      'burgan',
      'bank',
      '2025',
      'güncel',
      'faiz',
      'oranları',
      'kredi',
      'ürünleri',
      'dijital',
      'bankacılık',
      'rehberi',
    ],
    canonical: '/blog/burgan-bank',
  },
  content: [
    { type: 'heading', level: 1, text: 'Burgan Bank: Türkiye\'nin Büyüyen Bankacılık Devi' },
    { type: 'heading', level: 2, text: 'Burgan Bank Tarihçesi' },
    { type: 'paragraph', text: 'Burgan Bank , Türkiye finans sektörüne 2013 yılında giriş yapmış olup, kökleri 1975 yılına kadar uzanan uluslararası bir deneyime sahiptir. 2025 itibarıyla Türkiye\'de:' },
    { type: 'list', style: 'unordered', items: [
        '87 şube ile hizmet vermektedir',
        '1.2 milyon aktif müşteri portföyü bulunmaktadır',
        '45 milyar TL aktif büyüklüğe ulaşmıştır',
        'Dijital bankacılık kullanım oranı %73\'tür',
    ]},
    { type: 'heading', level: 2, text: '2025\'te Burgan Bank' },
    { type: 'paragraph', text: '2025 yılı stratejileri kapsamında Burgan Bank şu hedefleri belirlemiştir:' },
    { type: 'list', style: 'ordered', items: [
        'Müşteri deneyiminde dijital dönüşümü tamamlamak',
        'KOBİ bankacılığında pazar payını %15\'e çıkarmak',
        'Sürdürülebilir finans ürünlerini %40 artırmak',
        'Mobil bankacılık işlem hacmini 2 katına çıkarmak',
    ]},
    { type: 'heading', level: 3, text: 'Ekonomist Görüşü: Burgan Bank\'ın Yükselişi' },
    { type: 'paragraph', text: 'Finans analisti Zeynep Aktaş , ihtiyackredisi.com için yaptığı değerlendirmede:' },
    { type: 'heading', level: 2, text: 'Burgan Bank 2025 Mevduat Ürünleri: Paranızı En İyi Şekilde Değerlendirin' },
    { type: 'heading', level: 3, text: 'Vadeli Mevduat Hesapları' },
    { type: 'table', caption: '', headers: [
        'Vade Seçeneği',
        'TL Faiz Oranı',
        'USD Faiz Oranı',
        'EUR Faiz Oranı',
        'Minimum Bakiye',
        'Erken Çekim Oranı',
    ], rows: [
      ['1 Ay', '%22.00', '%1.50', '%0.80', '10.000 TL / 1.000 $/€', '%50'],
      ['3 Ay', '%25.00', '%2.00', '%1.20', '5.000 TL / 500 $/€', '%60'],
      ['6 Ay', '%28.00', '%2.50', '%1.50', '5.000 TL / 500 $/€', '%70'],
      ['12 Ay', '%32.00', '%3.00', '%2.00', '5.000 TL / 500 $/€', '%80'],
    ]},
    { type: 'paragraph', text: '100.000 TL\'nizi Burgan Bank\'ta 12 ay vadeli mevduata yatırdığınızda:' },
    { type: 'list', style: 'unordered', items: [
        'Yıllık faiz: %32',
        'Brüt getiri: 100.000 x 0.32 = 32.000 TL',
        'Stopaj kesintisi (%15): 32.000 x 0.15 = 4.800 TL',
        'Net getiri: 32.000 - 4.800 = 27.200 TL',
        'Vade sonu bakiye: 127.200 TL',
    ]},
    { type: 'paragraph', text: 'Karşılaştırma için: ING Bank hoşgeldin faizi hesaplama' },
    { type: 'list', style: 'ordered', items: [
        'Faiz oranları TCMB politikalarına göre değişebilir',
        'Döviz hesaplarında kur riski bulunmaktadır',
        'Erken çekimlerde faiz kaybı yaşanabilir',
        'BESK (Banka ve Sigorta Muameleleri Vergisi) kesintisi uygulanır',
        'Enflasyonun üzerinde getiri için reel faiz hesaplaması yapılmalı',
    ]},
    { type: 'heading', level: 3, text: 'Özel Mevduat Ürünleri' },
    { type: 'list', style: 'unordered', items: [
        '55 yaş üstüne özel',
        'Ek %1 faiz avantajı',
        'Ücretsiz sigorta paketi',
        'Esnek vade seçenekleri',
    ]},
    { type: 'list', style: 'unordered', items: [
        '18-25 yaş aralığı',
        'Düşük minimum bakiye (1.000 TL)',
        'Mobil uygulamada özel arayüz',
        'Kültür-sanat etkinliklerinde indirim',
    ]},
    { type: 'list', style: 'unordered', items: [
        'Şirketlere özel faiz oranları',
        'Nakit yönetim çözümleri',
        'Haftalık faiz ödemesi seçeneği',
        'Özel müşteri temsilcisi',
    ]},
    { type: 'heading', level: 2, text: 'Burgan Bank 2025 Kredi Ürünleri: İhtiyaçlarınıza Özel Çözümler' },
    { type: 'heading', level: 3, text: 'Bireysel Kredi Çeşitleri' },
    { type: 'list', style: 'unordered', items: [
        'Limit: 50.000 TL - 500.000 TL',
        'Vade: 12-36 ay',
        'Faiz Oranı: %2.19 - %2.89 aylık (KKDF ve BSMV dahil)',
        'Özel Kampanya: 2025 Mayıs\'a kadar ilk 3 ay %1.89 faiz',
        'Avantaj: 15 dakikada ön onay',
    ]},
    { type: 'list', style: 'unordered', items: [
        'Limit: Mülk değerinin %80\'i kadar',
        'Vade: 36-120 ay',
        'Faiz Oranı: %1.99 - %2.39 aylık',
        'Dijital Başvuru: E-imza ile tamamlanabilir',
        'Ek Hizmet: Ücretsiz ekspertiz',
    ]},
    { type: 'heading', level: 3, text: 'Kurumsal Kredi Çeşitleri' },
    { type: 'list', style: 'unordered', items: [
        'Limit: 500.000 TL - 5.000.000 TL',
        'Vade: 12-48 ay',
        'Faiz Oranı: %1.79 - %2.29 aylık',
        'Destek: İhracat yapan KOBİ\'lere ek %0.25 indirim',
        'Kolaylık: Nakit akışına göre esnek geri ödeme',
    ]},
    { type: 'list', style: 'unordered', items: [
        'Limit: 1.000.000 TL - 50.000.000 TL',
        'Vade: 24-60 ay',
        'Faiz Oranı: %1.69 - %2.09 aylık',
        'Teşvik: Yeşil yatırımlarda %0.30 ek indirim',
        'Avantaj: 6 ay ödemesiz dönem',
    ]},
    { type: 'heading', level: 3, text: 'Burgan Bank Kredi Başvuru Süreci' },
    { type: 'list', style: 'ordered', items: [
        'Online Ön Başvuru: Burgan Bank web sitesi veya mobil uygulama',
        'TCKN ve iletişim bilgileri',
        'Kredi tutarı ve vade tercihi',
        '15 dakikada ön onay sonucu',
        'Belge Teslimi: Kimlik fotokopisi',
        'Gelir belgesi (maaş bordrosu, vergi levhası)',
        'İkametgah belgesi',
        'Ek belgeler (konut kredisinde tapu, taşıt kredisinde ruhsat)',
        'Değerlendirme: Kredi notu kontrolü',
        'Gelir-gider analizi',
        'Güvence değerlendirmesi',
        'Maksimum 24 saat içinde sonuç',
        'Kredi Kullandırma: Sözleşme imzası',
        'Masrafların ödenmesi',
        'Paranın hesaba aktarılması (aynı gün)',
    ]},
    { type: 'paragraph', text: 'Karşılaştırma için: Halkbank kredi başvurusu süreci' },
    { type: 'heading', level: 3, text: 'Kredi Hesaplama Tablosu' },
    { type: 'table', caption: '', headers: [
        'Kredi Tutarı',
        '24 Ay (%2.19)',
        '36 Ay (%2.39)',
        '48 Ay (%2.59)',
        '60 Ay (%2.79)',
    ], rows: [
      ['50.000 TL', '2.632 TL', '1.961 TL', '1.598 TL', '1.382 TL'],
      ['100.000 TL', '5.263 TL', '3.922 TL', '3.196 TL', '2.764 TL'],
      ['250.000 TL', '13.158 TL', '9.805 TL', '7.990 TL', '6.910 TL'],
    ]},
    { type: 'paragraph', text: 'Finans Danışmanı Emre Demirci :' },
    { type: 'list', style: 'unordered', items: [
        'Erken kapama cezası olup olmadığını kontrol edin',
        'Sigorta zorunluluklarını öğrenin',
        'Faiz artış riskine karşı sabit faizli ürünleri değerlendirin',
        'Kredi notunuzu başvuru öncesi öğrenin',
    ]},
    { type: 'heading', level: 2, text: 'Burgan Bank 2025 Kredi Kartları: Akıllı Alışverişin Yeni Nesil Çözümleri' },
    { type: 'heading', level: 3, text: 'Kredi Kartı Çeşitleri' },
    { type: 'list', style: 'unordered', items: [
        'Yıllık ücret: 750 TL (ilk yıl ücretsiz)',
        'Nakit geri ödeme: %2.5',
        'Limit: 50.000 TL\'ye kadar',
        'Avantajlar: Lounge key, yolcu sigortası',
        'Puan: 100 TL\'de 5 puan',
    ]},
    { type: 'list', style: 'unordered', items: [
        'Yıllık ücret: 1.500 TL',
        'Nakit geri ödeme: %3.0',
        'Limit: 150.000 TL\'ye kadar',
        'Avantajlar: Kişisel asistan, golf kulübü',
        'Puan: 100 TL\'de 7 puan',
    ]},
    { type: 'list', style: 'unordered', items: [
        'Yıllık ücret: 250 TL',
        'Nakit geri ödeme: %1.5',
        'Limit: 30.000 TL\'ye kadar',
        'Avantajlar: Organik ürünlerde ek puan',
        'Puan: 100 TL\'de 3 puan',
    ]},
    { type: 'heading', level: 3, text: 'Kredi Kartı Avantajları' },
    { type: 'table', caption: '', headers: [
        'Kategori',
        'Platinum',
        'Infinite',
        'Eco',
    ], rows: [
      ['Yemek', '%5 ek puan', '%7 ek puan', '%3 ek puan'],
      ['Yolculuk', '%3 nakit iade', '%5 nakit iade', '%1 nakit iade'],
      ['Eğlence', '2x puan', '3x puan', '1.5x puan'],
      ['Online Alışveriş', '%4 nakit iade', '%6 nakit iade', '%2 nakit iade'],
    ]},
    { type: 'heading', level: 3, text: 'Kredi Kartı Başvuru Süreci' },
    { type: 'list', style: 'ordered', items: [
        'Online Başvuru: Burgan Bank web sitesi veya mobil uygulama',
        '1 dakikada doldurulabilen form',
        'Kredi notu sorgulaması',
        'Onay Süreci: Anında ön onay',
        '24 saat içinde kesin onay',
        'SMS ile bilgilendirme',
        'Kart Teslimi: 3 iş günü içinde kargo',
        'Ücretsiz teslimat',
        'Mobil uygulamadan aktifleştirme',
    ]},
    { type: 'paragraph', text: 'Karşılaştırma için: Garanti Bankası kredi kartı avantajları' },
    { type: 'heading', level: 3, text: 'Kredi Kartı Borç Yapılandırma' },
    { type: 'paragraph', text: 'Burgan Bank 2025 yılında kredi kartı borçları için esnek yapılandırma seçenekleri sunuyor' },
    { type: 'list', style: 'unordered', items: [
        'Taksitlendirme: 3-12 ay arası vade seçeneği',
        'Erteleme: 3 ay ödemesiz dönem',
        'Vade Farkı: %1.29-1.89 aylık faiz',
        'Avantaj: İlk yapılandırmada %0.50 indirim',
    ]},
    { type: 'list', style: 'ordered', items: [
        'Mobil uygulamadan "Borç Yapılandırma" seçeneği',
        'Yapılandırılacak tutarın belirlenmesi',
        'Vade tercihinin yapılması',
        'E-imza ile onay süreci',
        'Yeni ödeme planının oluşturulması',
    ]},
    { type: 'paragraph', text: 'Finansal Okuryazarlık Uzmanı Selma Yıldız :' },
    { type: 'heading', level: 2, text: 'Burgan Bank Dijital Bankacılık: 2025\'in En İnovatif Özellikleri' },
    { type: 'heading', level: 3, text: 'Mobil Uygulama Yenilikleri' },
    { type: 'list', style: 'unordered', items: [
        'Türkçe doğal dil işleme teknolojisi',
        '"Para transferi yap", "Fatura öde" gibi komutlar',
        'Kişisel harcama analizi sunma',
        '7/24 aktif destek',
    ]},
    { type: 'list', style: 'unordered', items: [
        'Otomatik harcama kategorilendirme',
        'Tasarruf önerileri',
        'Abonelik takip sistemi',
        'Öngörülebilir gelecek harcama analizi',
    ]},
    { type: 'heading', level: 3, text: 'Dijital Güvenlik Önlemleri' },
    { type: 'table', caption: '', headers: [
        'Özellik',
        'Açıklama',
        'Avantaj',
    ], rows: [
      ['Çok Faktörlü Kimlik Doğrulama', 'SMS + Biyometrik + Şifre', '%99.9 güvenlik'],
      ['Anormal İşlem Tespiti', 'Yapay zeka destekli', 'Şüpheli işlem uyarısı'],
      ['Sanal Kart', 'Online alışverişler için', 'Limit ve süre kısıtlaması'],
      ['Coğrafi Konum Doğrulama', 'GPS ile giriş kontrolü', 'Yetkisiz erişimi engeller'],
    ]},
    { type: 'heading', level: 3, text: 'Open Banking ve Üçüncü Parti Entegrasyonlar' },
    { type: 'list', style: 'unordered', items: [
        'Hepsiburada, Trendyol direkt ödeme',
        'Tek tıkla ödeme kolaylığı',
        'Ekstra puan avantajı',
    ]},
    { type: 'list', style: 'unordered', items: [
        'Papara, Paycell entegrasyonu',
        'Anlık bakiye görüntüleme',
        'Komisyonuz para transferi',
    ]},
    { type: 'list', style: 'unordered', items: [
        'Midpoint, İş Yatırım bağlantısı',
        'Tek ekranda portföy takibi',
        'Kolay fon aktarımı',
    ]},
    { type: 'paragraph', text: 'Dijital Bankacılık Danışmanı Caner Tekin :' },
    { type: 'list', style: 'unordered', items: [
        'Uygulama içi canlı destek 7/24 hizmet veriyor',
        'Yüz tanıma ile giriş saniyeler sürüyor',
        'Akıllı ödeme önerileri ile fatura unutma sorunu ortadan kalkıyor',
        'QR kod ile anında para transferi yapılabiliyor',
    ]},
    { type: 'heading', level: 2, text: 'Burgan Bank Müşteri Deneyimi: 2025\'te Hizmet Kalitesi' },
    { type: 'heading', level: 3, text: 'Şube Ağı ve Fiziksel Deneyim' },
    { type: 'list', style: 'unordered', items: [
        'Modern ve minimal tasarım',
        'Self servis bankacılık üniteleri',
        'Dijital asistan destekli işlemler',
        'Çocuklu aileler için oyun alanı',
    ]},
    { type: 'list', style: 'unordered', items: [
        'Private Banking: Yüksek gelirli bireyler',
        'GençBank: 18-25 yaş özel şubeler',
        'KadınBank: Kadın girişimcilere özel',
        'KOBİ Plaza: İşletmelere yönelik',
    ]},
    { type: 'heading', level: 3, text: 'Müşteri Hizmetleri' },
    { type: 'table', caption: '', headers: [
        'Kanal',
        'Hizmet Süresi',
        'Yanıt Süresi',
        'Dil Seçenekleri',
    ], rows: [
      ['Mobil Uygulama Canlı Destek', '7/24', 'Ort. 45 sn', 'Türkçe, İngilizce'],
      ['444 0 800', '08:00-24:00', 'Ort. 2 dk', 'Türkçe, İngilizce, Arapça'],
      ['E-posta', '7/24', 'Ort. 4 saat', 'Türkçe, İngilizce'],
      ['Şube', '09:00-17:00', 'Ort. 15 dk', 'Türkçe'],
    ]},
    { type: 'heading', level: 3, text: 'Müşteri Memnuniyeti Verileri' },
    { type: 'paragraph', text: '92%' },
    { type: 'paragraph', text: 'Dijital Bankacılık Memnuniyeti' },
    { type: 'paragraph', text: '88%' },
    { type: 'paragraph', text: 'Şube Hizmetleri Memnuniyeti' },
    { type: 'paragraph', text: '94%' },
    { type: 'paragraph', text: 'Mobil Uygulama Puanı' },
    { type: 'paragraph', text: 'Hizmet Tasarımı Danışmanı Aslıhan Korkmaz :' },
    { type: 'heading', level: 2, text: 'Burgan Bank Hakkında Sık Sorulan Sorular' },
    { type: 'heading', level: 3, text: 'Burgan Bank mevduat faiz oranları nasıl belirleniyor?' },
    { type: 'paragraph', text: 'Burgan Bank mevduat faiz oranları; TCMB politikaları, piyasa koşulları, enflasyon beklentileri ve bankanın fonlama ihtiyacı gibi faktörler dikkate alınarak belirlenir. 2025 yılı Mayıs ayı itibarıyla Burgan Bank TL mevduatta sektör ortalamasının %1-2 puan üzerinde faiz veriyor.' },
    { type: 'heading', level: 3, text: 'Burgan Bank kredi başvurusu için kredi notu kaç olmalı?' },
    { type: 'paragraph', text: 'Burgan Bank\'ın 2025 yılı kredi başvurularında aradığı minimum kredi notu 1.200 puandır. Ancak 1.400 puan ve üzeri müşteriler daha düşük faiz oranlarından yararlanabilir. Kredi notunuzu Findeks üzerinden öğrenebilirsiniz.' },
    { type: 'heading', level: 3, text: 'Burgan Bank\'ta hesap açmak için hangi belgeler gerekiyor?' },
    { type: 'paragraph', text: 'Burgan Bank\'ta 2025 yılında hesap açmak için gerekli belgeler: TCKN beyan eden geçerli kimlik belgesi İkametgah belgesi (e-devlet çıktısı kabul ediliyor) Gelir belgesi (maaş bordrosu, vergi levhası vb.) Bazı durumlarda ek belge istenebilir' },
    { type: 'heading', level: 3, text: 'Burgan Bank dijital bankacılık ücret alıyor mu?' },
    { type: 'paragraph', text: 'Burgan Bank 2025\'te temel dijital bankacılık işlemleri için ücret almamaktadır. Ancak özel bazı hizmetler (acuz EFT, anında havale gibi) için işlem başına 5-15 TL arasında ücretler uygulanabilir. Tam liste için resmi ücret tarifesini inceleyebilirsiniz.' },
    { type: 'heading', level: 3, text: 'Burgan Bank kredi kartı ekstreleri nasıl sorgulanır?' },
    { type: 'paragraph', text: 'Burgan Bank kredi kartı ekstrelerinizi: Mobil uygulama üzerinden İnternet bankacılığında "Kart İşlemleri" bölümünden 444 0 800 müşteri hizmetlerini arayarak Şubeye giderek sorgulayabilirsiniz' },
    { type: 'heading', level: 2, text: 'Burgan Bank 2025: Avantajlar ve Değerlendirme' },
    { type: 'heading', level: 3, text: 'Burgan Bank\'ın Güçlü Yönleri' },
    { type: 'list', style: 'unordered', items: [
        'Yüksek Mevduat Faizleri: Özellikle 12 ay vadede sektör lideri',
        'KOBİ Dostu Ürünler: İşletmelere özel esnek çözümler',
        'Dijital İnovasyon: Yapay zeka destekli bankacılık',
        'Hızlı Kredi Onayı: 15 dakikada ön onay imkanı',
    ]},
    { type: 'list', style: 'unordered', items: [
        'Müşteri Odaklı Tasarım: Segmentlere özel hizmetler',
        'Şube Deneyimi: Modern ve konforlu fiziksel ağ',
        'Güvenlik: Çok katmanlı koruma sistemi',
        'Ödül Programı: Geniş kapsamlı puan avantajları',
    ]},
    { type: 'heading', level: 3, text: 'Diğer Bankalarla Karşılaştırma' },
    { type: 'table', caption: '', headers: [
        'Kriter',
        'Burgan Bank',
        'Ziraat Bankası',
        'İş Bankası',
        'Garanti BBVA',
    ], rows: [
      ['12 Ay TL Mevduat', '%32.00', '%30.50', '%31.25', '%30.75'],
      ['İhtiyaç Kredisi (60 Ay)', '%2.79', '%2.85', '%2.89', '%2.95'],
      ['Kredi Kartı Nakit İade', '%3.00', '%1.50', '%2.25', '%2.75'],
      ['Mobil Uygulama Puanı', '4.8/5', '4.5/5', '4.6/5', '4.7/5'],
    ]},
    { type: 'heading', level: 3, text: 'Kimler Burgan Bank\'ı Tercih Etmeli?' },
    { type: 'list', style: 'unordered', items: [
        'Yüksek mevduat faizi',
        'Döviz ve altın hesap seçenekleri',
        'Güvenli yatırım ortamı',
    ]},
    { type: 'list', style: 'unordered', items: [
        'Esnek kredi ödeme planları',
        'Özel müşteri temsilcisi',
        'Nakit yönetim çözümleri',
    ]},
    { type: 'list', style: 'unordered', items: [
        'Gelişmiş mobil uygulama',
        'Yapay zeka destekli özellikler',
        'Hızlı ve güvenli işlemler',
    ]},
    { type: 'paragraph', text: 'Burgan Bank, 2025 yılında özellikle mevduat faiz oranları ve dijital bankacılık alanında sektörün önde gelen kurumlarından biri olarak öne çıkıyor. KOBİ\'lere yönelik finansman çözümleri ve yenilikçi müşteri deneyimi yaklaşımıyla fark yaratan banka, genç nüfusun da ilgisini çekmeyi başarıyor.' },
    { type: 'paragraph', text: 'Ancak, şube ağının diğer büyük bankalara göre daha sınırlı olduğu ve bazı bölgelerde fiziksel hizmete erişimin zor olabileceği unutulmamalı. Daha fazla karşılaştırma için ihtiyackredisi.com blog sayfamızı ziyaret edebilirsiniz.' },
    { type: 'heading', level: 3, text: 'Editör' },
    { type: 'paragraph', text: 'Emre Şahin' },
    { type: 'paragraph', text: '10+ yıllık finans deneyimi' },
    { type: 'heading', level: 3, text: 'Yazar' },
    { type: 'paragraph', text: 'Deniz Arslan' },
    { type: 'paragraph', text: 'Bankacılık ve Finans Uzmanı' },
    { type: 'heading', level: 3, text: 'Röportajı Yapan' },
    { type: 'paragraph', text: 'Selim Korkmaz' },
    { type: 'paragraph', text: 'Finans Muhabiri' },
    { type: 'paragraph', text: '© 2025 ihtiyackredisi.com - Tüm hakları saklıdır. Sunulan bilgiler yatırım tavsiyesi niteliğinde olmayıp araştımalar neticesinde editör ve yazarlarımız tarafından derlenip bilgi amaçlı sunulmaktadır.' },
  ],
  faq: [
    { question: 'Burgan Bank mevduat faiz oranları nasıl belirleniyor?', answer: 'Burgan Bank mevduat faiz oranları; TCMB politikaları, piyasa koşulları, enflasyon beklentileri ve bankanın fonlama ihtiyacı gibi faktörler dikkate alınarak belirlenir. 2025 yılı Mayıs ayı itibarıyla Burgan Bank TL mevduatta sektör ortalamasının %1-2 puan üzerinde faiz veriyor.' },
    { question: 'Burgan Bank kredi başvurusu için kredi notu kaç olmalı?', answer: 'Burgan Bank\'ın 2025 yılı kredi başvurularında aradığı minimum kredi notu 1.200 puandır. Ancak 1.400 puan ve üzeri müşteriler daha düşük faiz oranlarından yararlanabilir. Kredi notunuzu Findeks üzerinden öğrenebilirsiniz.' },
    { question: 'Burgan Bank\'ta hesap açmak için hangi belgeler gerekiyor?', answer: 'Burgan Bank\'ta 2025 yılında hesap açmak için gerekli belgeler: TCKN beyan eden geçerli kimlik belgesi İkametgah belgesi (e-devlet çıktısı kabul ediliyor) Gelir belgesi (maaş bordrosu, vergi levhası vb.) Bazı durumlarda ek belge istenebilir' },
    { question: 'Burgan Bank dijital bankacılık ücret alıyor mu?', answer: 'Burgan Bank 2025\'te temel dijital bankacılık işlemleri için ücret almamaktadır. Ancak özel bazı hizmetler (acuz EFT, anında havale gibi) için işlem başına 5-15 TL arasında ücretler uygulanabilir. Tam liste için resmi ücret tarifesini inceleyebilirsiniz.' },
    { question: 'Burgan Bank kredi kartı ekstreleri nasıl sorgulanır?', answer: 'Burgan Bank kredi kartı ekstrelerinizi: Mobil uygulama üzerinden İnternet bankacılığında "Kart İşlemleri" bölümünden 444 0 800 müşteri hizmetlerini arayarak Şubeye giderek sorgulayabilirsiniz' },
  ],
  related: [],
}
