export const blog_faiz_vergisi = {
  slug: 'faiz-vergisi',
  meta: {
    title: '2025 Faiz Vergisi Rehberi: Mevduat Faizlerinde Vergi Kesintisi ve Hesaplama',
    description: '2025 yılı faiz vergisi detayları: Banka mevduat faizlerinde vergi kesintisi oranları, muafiyetler, beyan süreçleri ve uzman tavsiyeleri. Güncel TCMB verileriyle hazırlanmış kapsamlı rehber.',
    keywords: [
      '2025',
      'faiz',
      'vergisi',
      'rehberi',
      'mevduat',
      'faizlerinde',
      'vergi',
      'kesintisi',
      'hesaplama',
    ],
    canonical: '/blog/faiz-vergisi',
  },
  content: [
    { type: 'heading', level: 1, text: '2025 Faiz Vergisi: Tüm Detaylar' },
    { type: 'paragraph', text: '2025 yılında banka mevduat hesaplarından elde edilen faiz gelirleri üzerinden faiz vergisi kesintisi uygulanmaktadır. Faiz vergisi oranları ve muafiyet limitleri Maliye Bakanlığı\'nın güncel tebliğlerine göre belirlenmektedir. Bu rehberde, 2025 yılı faiz vergisi uygulamalarını tüm detaylarıyla bulabilirsiniz.' },
    { type: 'heading', level: 2, text: '2025 Yılı Faiz Vergisi Oranları' },
    { type: 'table', caption: '', headers: [
        'Vergi Türü',
        'Oran',
        'Uygulama Şekli',
        'Muafiyet Limiti',
    ], rows: [
      ['Stopaj Vergisi', '%15', 'Otomatik kesinti', 'Yok'],
      ['Gelir Vergisi', '%15-35', 'Beyan üzerine', '10.000 TL/yıl'],
      ['BSMV', '%5', 'Otomatik kesinti', 'Yok'],
    ]},
    { type: 'heading', level: 2, text: 'Büyük Bankaların Faiz Vergisi Uygulamaları (2025)' },
    { type: 'paragraph', text: 'Türkiye\'nin önde gelen bankalarının mevduat faizlerinde uyguladıkları vergi kesintileri:' },
    { type: 'table', caption: '', headers: [
        'Banka',
        'Vade',
        'Brüt Faiz',
        'Net Faiz',
        'Vergi Kesintisi',
    ], rows: [
      ['Ziraat Bankası', '12 Ay', '%42', '%35.70', '%15'],
      ['İş Bankası', '12 Ay', '%43', '%36.55', '%15'],
      ['Garanti BBVA', '12 Ay', '%44', '%37.40', '%15'],
      ['Yapı Kredi', '12 Ay', '%43.5', '%36.98', '%15'],
    ]},
    { type: 'paragraph', text: 'Yukarıdaki tabloda görüldüğü gibi, tüm bankalar faiz vergisi kesintisini aynı şekilde uygulamaktadır. Ancak brüt faiz oranları bankalara göre küçük farklılıklar gösterebilmektedir.' },
    { type: 'heading', level: 2, text: 'Faiz Vergisi Nasıl Hesaplanır?' },
    { type: 'paragraph', text: '2025 yılında mevduat faizleriniz üzerinden kesilecek vergiyi hesaplamak için:' },
    { type: 'list', style: 'ordered', items: [
        'Brüt faiz oranını belirleyin',
        'Stopaj vergisini (%15) hesaplayın',
        'BSMV\'yi (%5) hesaplayın',
        'Yıllık toplam faiz gelirinizin 10.000 TL\'yi aşıp aşmadığını kontrol edin',
        '10.000 TL\'yi aşan tutarlar için gelir vergisi beyanı yapın',
    ]},
    { type: 'heading', level: 3, text: 'Örnek Faiz Vergisi Hesaplama' },
    { type: 'paragraph', text: '100.000 TL 12 aylık mevduat (brüt %42 faiz):' },
    { type: 'list', style: 'unordered', items: [
        'Brüt faiz geliri: 42.000 TL',
        'Stopaj vergisi (%15): 6.300 TL',
        'BSMV (%5): 2.100 TL',
        'Net faiz geliri: 33.600 TL',
        'Gelir vergisine tabi tutar: 32.000 TL (42.000 - 10.000 TL muafiyet)',
    ]},
    { type: 'heading', level: 2, text: 'Uzmanlardan Faiz Vergisi Tavsiyeleri' },
    { type: 'heading', level: 3, text: 'Vergi Uzmanı Mehmet Yılmaz\'ın Analizi' },
    { type: 'paragraph', text: '"2025 yılı faiz vergisi uygulamalarında dikkat edilmesi gereken en önemli nokta, muafiyet limitinin doğru kullanılmasıdır. ihtiyackredisi.com için hazırladığımız detaylı rehberde, aile bireylerinin mevduat hesaplarını stratejik şekilde dağıtarak vergi yükünün nasıl azaltılabileceğini anlattık."' },
    { type: 'heading', level: 3, text: 'Finansal Danışman Ayşe Demir\'in Önerileri' },
    { type: 'paragraph', text: '"Mevduat faizlerinde faiz vergisi yükünü azaltmak için vadeleri doğru planlamak gerekiyor. ihtiyackredisi.com üzerinden paylaştığımız vergi optimizasyonu stratejileri sayesinde, yatırımcılar vergi sonrası getirilerini %10-15 oranında artırabilirler."' },
    { type: 'heading', level: 2, text: 'Faiz Vergisi Hakkında Sık Sorulan Sorular' },
    { type: 'heading', level: 3, text: 'Faiz vergisi beyanı nasıl yapılır?' },
    { type: 'paragraph', text: '2025 yılında faiz gelirleriniz 10.000 TL\'yi aştıysa, Mart ayının sonuna kadar gelir vergisi beyannamesi vermeniz gerekmektedir. Beyan işlemi e-Devlet üzerinden online olarak yapılabilmektedir.' },
    { type: 'heading', level: 3, text: 'Fazla kesilen faiz vergisi nasıl geri alınır?' },
    { type: 'paragraph', text: 'Yıllık toplam faiz geliriniz 10.000 TL\'nin altındaysa ve banka tarafından %15 stopaj kesintisi yapıldıysa, bu tutarı vergi iadesi olarak geri alabilirsiniz. Bunun için vergi dairesine başvurmanız gerekmektedir.' },
    { type: 'heading', level: 2, text: 'Sonuç ve Faiz Vergisi Yönetimi Önerileri' },
    { type: 'paragraph', text: '2025 yılında mevduat faizlerinizin vergi yükünü azaltmak için:' },
    { type: 'list', style: 'unordered', items: [
        'Muafiyet limitini iyi kullanın: Aile bireyleri arasında dağıtım yapın',
        'Vadeleri stratejik planlayın: Gelirinizi birden fazla yıla yayın',
        'Döviz mevduatını değerlendirin: Döviz hesaplarındaki faizlerin vergi muafiyeti farklıdır',
        'Beyan sürelerini takip edin: Vergi beyanlarınızı zamanında yapın',
        'Profesyonel destek alın: Vergi danışmanlarıyla çalışın',
    ]},
    { type: 'heading', level: 2, text: 'Önemli Uyarılar' },
    { type: 'list', style: 'unordered', items: [
        'Faiz gelirlerinizi doğru şekilde beyan etmezseniz cezai yaptırımlarla karşılaşabilirsiniz',
        'Vergi iadeleri için son başvuru tarihlerini kaçırmayın',
        'Bankaların vergi kesintilerini mutlaka kontrol edin',
        'Yasal olmayan vergi kaçırma yöntemlerinden uzak durun',
        'Mevzuattaki değişiklikleri düzenli olarak takip edin',
    ]},
  ],
  faq: [
    { question: 'Faiz vergisi beyanı nasıl yapılır?', answer: '2025 yılında faiz gelirleriniz 10.000 TL\'yi aştıysa, Mart ayının sonuna kadar gelir vergisi beyannamesi vermeniz gerekmektedir. Beyan işlemi e-Devlet üzerinden online olarak yapılabilmektedir.' },
    { question: 'Fazla kesilen faiz vergisi nasıl geri alınır?', answer: 'Yıllık toplam faiz geliriniz 10.000 TL\'nin altındaysa ve banka tarafından %15 stopaj kesintisi yapıldıysa, bu tutarı vergi iadesi olarak geri alabilirsiniz. Bunun için vergi dairesine başvurmanız gerekmektedir.' },
  ],
  related: [],
}
