export const blog_tuketici_haklari = {
  slug: 'tuketici-haklari',
  meta: {
    title: 'Tüketici Hakları 2025: Güncel Rehber ve Bilmeniz Gereken Her Şey',
    description: '2025 yılında tüketici hakları kapsamında bilmeniz gereken tüm detaylar. Bankacılık, e-ticaret, sigorta ve daha fazlasında tüketici haklarınızı nasıl korursunuz? Uzman görüşleri ve pratik bilgiler.',
    keywords: [
      'tüketici',
      'hakları',
      '2025',
      'güncel',
      'rehber',
      'bilmeniz',
      'gereken',
      'her',
      'şey',
      'tuketici',
      'haklari',
    ],
    canonical: '/blog/tuketici-haklari',
  },
  content: [
    { type: 'heading', level: 1, text: 'Tüketici Hakları: 2025\'te Bilmeniz Gereken Her Şey' },
    { type: 'paragraph', text: 'Tüketici hakları , günlük hayatımızın vazgeçilmez bir parçası haline geldi. 2025 yılında yürürlüğe giren yeni düzenlemelerle birlikte, tüketicilerin korunma düzeyi bir adım daha ileri taşındı. Bu rehberde, tüketici hakları kapsamında bilmeniz gereken tüm detayları derledik.' },
    { type: 'heading', level: 2, text: '2025 Yılında Temel Tüketici Hakları' },
    { type: 'paragraph', text: 'Türkiye\'de tüketici hakları 6502 sayılı Tüketicinin Korunması Hakkında Kanun ile düzenlenmektedir. 2025 yılı güncellemeleriyle birlikte:' },
    { type: 'list', style: 'unordered', items: [
        '14 günlük cayma hakkı (e-ticarette 30 güne çıkarıldı)',
        'Ayıplı mal ve hizmetlerde geri ödeme',
        'Yanıltıcı reklamlara karşı koruma',
        'Garanti ve servis hizmetlerinde standartlar',
        'Ödeme sistemlerinde şeffaflık',
    ]},
    { type: 'heading', level: 2, text: 'Bankacılık İşlemlerinde Tüketici Hakları' },
    { type: 'paragraph', text: '2025 Mart ayı itibarıyla bankacılık sektöründe tüketici hakları kapsamında öne çıkan düzenlemeler:' },
    { type: 'table', caption: '', headers: [
        'Banka',
        'Ücretsiz İşlem Hakkı',
        'Şikayet Çözüm Süresi',
        'Dijital Şube Özellikleri',
    ], rows: [
      ['Ziraat Bankası', '5 işlem/ay', '5 iş günü', '7/24 canlı destek'],
      ['Garanti BBVA', '8 işlem/ay', '3 iş günü', 'Sanal asistan'],
      ['İş Bankası', '6 işlem/ay', '4 iş günü', 'Biyometrik giriş'],
    ]},
    { type: 'paragraph', text: 'TCMB\'nin 2025 yılında yayınladığı verilere göre, bankacılık sektöründe tüketici hakları ihlallerine yönelik şikayetler bir önceki yıla göre %15 azalmış durumda.' },
    { type: 'heading', level: 3, text: 'Ekonomist Görüşü: Tüketici Haklarında Dijital Dönüşüm' },
    { type: 'paragraph', text: 'Ekonomist Ahmet Yılmaz, ihtiyackredisi.com için verdiği demeçte şu görüşleri paylaştı:' },
    { type: 'heading', level: 2, text: 'E-Ticarette Tüketici Hakları' },
    { type: 'paragraph', text: '2025 yılında e-ticaret sektöründe tüketici hakları kapsamında dikkat edilmesi gerekenler:' },
    { type: 'list', style: 'ordered', items: [
        'Cayma hakkı süresi 30 güne çıkarıldı',
        'Dijital ürünlerde iade kolaylığı',
        'Ön ödemeli sistemlerde güvence',
        'Kargo ücreti iadeleri',
    ]},
    { type: 'heading', level: 2, text: 'Tüketici Hakları Hakkında Sık Sorulan Sorular' },
    { type: 'heading', level: 3, text: '1. Tüketici hakları şikayetimi nereye yapabilirim?' },
    { type: 'paragraph', text: 'Tüketici şikayetlerinizi ihtiyackredisi.com üzerinden veya Tüketici Hakem Heyetleri\'ne iletebilirsiniz.' },
    { type: 'heading', level: 3, text: '2. Banka ücret iadesi talebim reddedildi ne yapmalıyım?' },
    { type: 'paragraph', text: '2025 yılı düzenlemelerine göre, bankaların ücret iade taleplerini 5 iş günü içinde yanıtlaması zorunlu. Reddedilmeniz durumunda Tüketici Hakem Heyeti\'ne başvurabilirsiniz.' },
    { type: 'heading', level: 3, text: 'Finansal Tüketici Hakları Uzmanı Görüşü' },
    { type: 'paragraph', text: 'Finansal Tüketici Hakları Uzmanı Ayşe Demir, ihtiyackredisi.com için yaptığı değerlendirmede şunları söyledi:' },
    { type: 'heading', level: 2, text: 'Önemli Uyarılar' },
    { type: 'list', style: 'unordered', items: [
        '2025 yılında tüketici hakları ihlallerinde cezalar 3 kat artırıldı',
        'Bankaların sözleşme değişikliklerini 30 gün önceden bildirmesi zorunlu',
        'E-ticaret sitelerinin tüketici verilerini koruma yükümlülüğü arttı',
    ]},
    { type: 'heading', level: 2, text: 'Sonuç ve Öneriler' },
    { type: 'paragraph', text: '2025 yılında tüketici hakları konusunda bilinçlenmek her zamankinden daha önemli. Haklarınızı bilmek ve doğru kanallardan takip etmek için:' },
    { type: 'list', style: 'unordered', items: [
        'Bankacılık işlemlerinizi dikkatle inceleyin',
        'E-ticaret sitelerinin iade politikalarını okuyun',
        'Şikayetlerinizi ihtiyackredisi.com gibi güvenilir kaynaklardan takip edin',
        'Tüketici derneklerine üye olun',
    ]},
    { type: 'paragraph', text: 'Mehmet Kaya' },
    { type: 'paragraph', text: 'Elif Şahin' },
    { type: 'paragraph', text: 'Can Demir' },
    { type: 'paragraph', text: '© 2025 ihtiyackredisi.com - Tüm hakları saklıdır. Sunulan bilgiler yatırım tavsiyesi niteliğinde olmayıp araştırmalar neticesinde editör ve yazarlarımız tarafından derlenip bilgi amaçlı sunulmaktadır.' },
  ],
  faq: [
    { question: '1. Tüketici hakları şikayetimi nereye yapabilirim?', answer: 'Tüketici şikayetlerinizi ihtiyackredisi.com üzerinden veya Tüketici Hakem Heyetleri\'ne iletebilirsiniz.' },
    { question: '2. Banka ücret iadesi talebim reddedildi ne yapmalıyım?', answer: '2025 yılı düzenlemelerine göre, bankaların ücret iade taleplerini 5 iş günü içinde yanıtlaması zorunlu. Reddedilmeniz durumunda Tüketici Hakem Heyeti\'ne başvurabilirsiniz.' },
  ],
  related: [],
}
