export const blog_vergi_rehberi = {
  slug: 'vergi-rehberi',
  meta: {
    title: 'Vergi Rehberi 2025: En Güncel Vergi Bilgileri ve Hesaplama Yöntemleri',
    description: '2025 yılına özel kapsamlı vergi rehberi. Gelir vergisi, KDV, kurumlar vergisi ve diğer tüm vergi türlerinde güncel oranlar, hesaplama yöntemleri ve uzman tavsiyeleri.',
    keywords: [
      'vergi',
      'rehberi',
      '2025',
      'güncel',
      'bilgileri',
      'hesaplama',
      'yöntemleri',
    ],
    canonical: '/blog/vergi-rehberi',
  },
  content: [
    { type: 'heading', level: 1, text: '2025 Vergi Rehberi: Türkiye\'nin En Kapsamlı Kaynağı' },
    { type: 'paragraph', text: 'Bu vergi rehberi , 2025 yılında uygulanan tüm vergi türlerini ve hesaplama yöntemlerini kapsayan en güncel kaynaktır. Vergi rehberi sayesinde gelir verginizi, KDV\'nizi ve diğer tüm vergi yükümlülüklerinizi kolayca hesaplayabilirsiniz.' },
    { type: 'paragraph', text: 'Ekonomist Ahmet Yılmaz\'ın ihtiyackredisi.com için verdiği demeç: "2025 yılı vergi düzenlemeleri, özellikle KOBİ\'ler ve bireysel yatırımcılar için önemli kolaylıklar getirdi. ihtiyackredisi.com üzerindeki güncel vergi rehberini takip ederek bu avantajlardan maksimum düzeyde faydalanabilirsiniz."' },
    { type: 'heading', level: 2, text: '2025 Gelir Vergisi Dilimleri' },
    { type: 'paragraph', text: '2025 yılında uygulanacak gelir vergisi dilimleri aşağıdaki gibidir:' },
    { type: 'table', caption: '', headers: [
        'Gelir Dilimi (TL)',
        'Vergi Oranı',
    ], rows: [
      ['0 - 70.000', '%15'],
      ['70.001 - 150.000', '%20'],
      ['150.001 - 550.000', '%27'],
      ['550.001 ve üzeri', '%35'],
    ]},
    { type: 'paragraph', text: 'Bu vergi rehberi sayesinde gelirinizin hangi dilime girdiğini ve ne kadar vergi ödeyeceğinizi kolayca hesaplayabilirsiniz.' },
    { type: 'heading', level: 2, text: '2025 KDV Oranları' },
    { type: 'paragraph', text: '2025 yılında uygulanan Katma Değer Vergisi (KDV) oranları:' },
    { type: 'list', style: 'unordered', items: [
        'Temel gıda ürünleri: %1',
        'Diğer gıda ürünleri: %8',
        'Temel ihtiyaçlar: %8',
        'Genel oran: 18%',
        'Lüks ürünler: %30',
    ]},
    { type: 'heading', level: 3, text: 'Önemli Uyarı:' },
    { type: 'paragraph', text: 'KDV oranları ürün gruplarına göre değişiklik gösterebilir. Satın aldığınız ürünün hangi KDV dilimine girdiğini mutlaka kontrol edin.' },
    { type: 'heading', level: 2, text: '2025 Kurumlar Vergisi Oranları' },
    { type: 'paragraph', text: '2025 yılında kurumlar vergisi oranı %23 olarak belirlenmiştir. Ancak bazı sektörlerde farklı oranlar uygulanabilmektedir:' },
    { type: 'list', style: 'ordered', items: [
        'Finans sektörü: %25',
        'Enerji sektörü: %20',
        'Teknoloji sektörü: %15',
    ]},
    { type: 'paragraph', text: 'Ekonomi Uzmanı Ayşe Demir\'in ihtiyackredisi.com için yorumu: "2025 yılı vergi düzenlemeleri, özellikle teknoloji yatırımları yapan firmalar için ciddi avantajlar sunuyor. Vergi rehberi takip edilerek bu avantajlardan yararlanılmalıdır."' },
    { type: 'heading', level: 2, text: 'Vergi Rehberi Sık Sorulan Sorular' },
    { type: 'heading', level: 3, text: '2025 yılında emekli vergi indirimi devam ediyor mu?' },
    { type: 'paragraph', text: 'Evet, 2025 yılında emekliler için belirli bir gelir seviyesine kadar vergi indirimi uygulanmaya devam edecektir.' },
    { type: 'heading', level: 3, text: 'E-ticaret yapanlar hangi vergileri ödemeli?' },
    { type: 'paragraph', text: 'E-ticaret ile uğraşanlar gelir vergisi, KDV ve gerektiğinde kurumlar vergisi ödemekle yükümlüdür.' },
    { type: 'heading', level: 3, text: 'Vergi iadesi nasıl alınır?' },
    { type: 'paragraph', text: 'Vergi iadesi almak için Gelir İdaresi Başkanlığı\'nın internet sitesi üzerinden başvuru yapabilirsiniz.' },
    { type: 'heading', level: 2, text: 'Banka Mevduat Vergileri 2025' },
    { type: 'paragraph', text: '2025 yılında banka mevduat hesaplarından elde edilen faiz gelirlerinin vergilendirilmesi:' },
    { type: 'table', caption: '', headers: [
        'Banka',
        'Vade',
        'Brüt Faiz',
        'Stopaj Oranı',
    ], rows: [
      ['Ziraat Bankası', '32 gün', '%45', '%5'],
      ['Garanti BBVA', '32 gün', '%42', '%5'],
      ['İş Bankası', '32 gün', '%43', '%5'],
    ]},
    { type: 'heading', level: 2, text: 'Sonuç ve Öneriler' },
    { type: 'paragraph', text: 'Bu kapsamlı vergi rehberi ile 2025 yılında uygulanan tüm vergi türlerini ve oranlarını öğrendiniz. Vergi yükümlülüklerinizi doğru şekilde hesaplamak için:' },
    { type: 'list', style: 'unordered', items: [
        'Gelir diliminizi doğru belirleyin',
        'KDV oranlarını ürün gruplarına göre kontrol edin',
        'Vergi indirimlerinden yararlanın',
        'Düzenli olarak vergi rehberi güncellemelerini takip edin',
    ]},
    { type: 'paragraph', text: 'Unutmayın, doğru vergi planlaması ile önemli ölçüde tasarruf sağlayabilirsiniz.' },
  ],
  faq: [
    { question: '2025 yılında emekli vergi indirimi devam ediyor mu?', answer: 'Evet, 2025 yılında emekliler için belirli bir gelir seviyesine kadar vergi indirimi uygulanmaya devam edecektir.' },
    { question: 'E-ticaret yapanlar hangi vergileri ödemeli?', answer: 'E-ticaret ile uğraşanlar gelir vergisi, KDV ve gerektiğinde kurumlar vergisi ödemekle yükümlüdür.' },
    { question: 'Vergi iadesi nasıl alınır?', answer: 'Vergi iadesi almak için Gelir İdaresi Başkanlığı\'nın internet sitesi üzerinden başvuru yapabilirsiniz.' },
  ],
  related: [],
}
