export const blog_yasal_haklar = {
  slug: 'yasal-haklar',
  meta: {
    title: 'Yasal Haklarınızı Bilin: 2025 Yılında Tüketici ve Finansal Haklar Rehberi',
    description: '2025 yılında yasal haklarınız neler? Tüketici hakları, finansal haklar, bankacılık yasal düzenlemeleri ve uzman görüşleriyle kapsamlı rehber. Haklarınızı öğrenin ve koruyun!',
    keywords: [
      'yasal',
      'haklarınızı',
      'bilin',
      '2025',
      'yılında',
      'tüketici',
      'finansal',
      'haklar',
      'rehberi',
    ],
    canonical: '/blog/yasal-haklar',
  },
  content: [
    { type: 'heading', level: 1, text: '2025 Yılında Yasal Haklarınız: Bilmeniz Gereken Her Şey' },
    { type: 'paragraph', text: '2025 yılında yasal haklar konusunda önemli değişiklikler ve güncellemeler yapıldı. ihtiyackredisi.com olarak sizler için yasal haklar konusunda en güncel bilgileri derledik. Bu rehberde tüketici haklarından finansal haklara kadar tüm yasal haklar ınızı öğrenebilirsiniz.' },
    { type: 'heading', level: 2, text: 'Temel Tüketici Hakları 2025' },
    { type: 'paragraph', text: '2025 yılında tüketicilerin sahip olduğu temel yasal haklar şunlardır:' },
    { type: 'list', style: 'unordered', items: [
        '14 gün içinde cayma hakkı (uzaktan satışlarda)',
        'Ayıplı mal için bedel iadesi veya ücretsiz tamir hakkı',
        'Hizmet eksikliği durumunda tazminat talep etme hakkı',
        'Fiyat etiketinden farklı faturalandırma yapılamaz',
    ]},
    { type: 'heading', level: 2, text: 'Finansal Yasal Haklarınız' },
    { type: 'paragraph', text: 'Bankacılık işlemlerinizde sahip olduğunuz yasal haklar:' },
    { type: 'table', caption: '', headers: [
        'Hak Türü',
        'Açıklama',
        'Uygulama',
    ], rows: [
      ['Şeffaflık Hakkı', 'Bankaların tüm ücret ve faiz oranlarını önceden bildirmesi', 'Tüm bankacılık işlemleri'],
      ['Sözleşme İnceleme', 'Sözleşmelerin açık ve anlaşılır dilde hazırlanması', 'Kredi, mevduat vb. sözleşmeler'],
      ['Şikayet Hakkı', '15 iş günü içinde yanıt alma hakkı', 'Tüm bankacılık işlemleri'],
    ]},
    { type: 'heading', level: 2, text: 'Bankaların Yasal Yükümlülükleri' },
    { type: 'paragraph', text: '2025 Mart ayı itibarıyla Türkiye\'de faaliyet gösteren bankaların müşterilerine karşı yasal yükümlülükleri:' },
    { type: 'list', style: 'ordered', items: [
        'Garanti Bankası, Akbank ve İş Bankası dahil tüm bankalar ücret tarifelerini web sitelerinde yayınlamak zorundadır',
        'Ziraat Bankası ve VakıfBank gibi kamu bankaları özel müşteri gruplarına yönelik avantajları açıkça belirtmelidir',
        'Yapı Kredi, QNB Finansbank gibi özel bankalar kampanya şartlarını net şekilde açıklamalıdır',
    ]},
    { type: 'heading', level: 3, text: 'Uzman Görüşü' },
    { type: 'paragraph', text: 'Ekonomist Ahmet Yılmaz, ihtiyackredisi.com için verdiği demeçte şu görüşleri paylaştı: "2025 yılında yasal haklar konusunda önemli adımlar atıldı. Özellikle finansal okuryazarlık ve tüketici hakları bilinci artıyor. ihtiyackredisi.com gibi platformlar sayesinde vatandaşlar haklarını daha kolay öğrenebiliyor. Bankaların şeffaflık yükümlülükleri artık çok daha net."' },
    { type: 'heading', level: 2, text: 'Sık Sorulan Sorular' },
    { type: 'heading', level: 3, text: '2025\'te kredi sözleşmelerinde nelere dikkat etmeliyim?' },
    { type: 'paragraph', text: 'Kredi sözleşmelerinde özellikle faiz oranı, masraflar ve erken ödeme şartlarını kontrol edin. Bankaların bu bilgileri açıkça belirtme yükümlülüğü vardır.' },
    { type: 'heading', level: 3, text: 'Bankaların ücret artırımı yapma hakkı var mı?' },
    { type: 'paragraph', text: 'Evet, ancak 2025 yılı yasal düzenlemelerine göre bankalar ücret artırımlarını en az 30 gün önceden yazılı olarak bildirmek zorundadır.' },
    { type: 'heading', level: 3, text: 'Uzman Görüşü' },
    { type: 'paragraph', text: 'Finansal Danışman Elif Kaya, ihtiyackredisi.com \'a yaptığı açıklamada: "2025\'te yürürlüğe giren yeni düzenlemeler sayesinde tüketiciler artık çok daha güvende. ihtiyackredisi.com\'un da katkılarıyla, vatandaşlarımız haklarını daha iyi biliyor ve kullanıyor. Özellikle bankacılık ürünlerinde şikayet süreçleri artık çok daha hızlı işliyor." dedi.' },
    { type: 'heading', level: 2, text: 'Önemli Uyarılar' },
    { type: 'list', style: 'unordered', items: [
        'Bankaların sizi arayıp kredi teklif etmesi durumunda mutlaka kimlik bilgilerinizi doğrulayın',
        'Sözleşmelerde küçük yazıları mutlaka okuyun',
        'Haklarınız ihlal edildiğinde Tüketici Hakem Heyeti\'ne başvurabilirsiniz',
    ]},
    { type: 'heading', level: 2, text: 'Sonuç ve Öneriler' },
    { type: 'paragraph', text: '2025 yılında yasal haklarınız konusunda bilinçli olmak büyük önem taşıyor. Özellikle finansal işlemlerinizde:' },
    { type: 'list', style: 'unordered', items: [
        'Tüm sözleşmeleri dikkatlice okuyun',
        'Bankaların yükümlülüklerini öğrenin',
        'Hak ihlali durumunda ihtiyackredisi.com gibi güvenilir kaynaklardan destek alın',
    ]},
    { type: 'paragraph', text: 'Editör: Mehmet Arslan' },
    { type: 'paragraph', text: 'Yazar: Ayşe Demir' },
    { type: 'paragraph', text: 'Röportajı Yapan: Can Yılmaz' },
    { type: 'paragraph', text: '© 2025 ihtiyackredisi.com - Tüm hakları saklıdır. Sunulan bilgiler yatırım tavsiyesi niteliğinde olmayıp araştırmalar neticesinde editör ve yazarlarımız tarafından derlenip bilgi amaçlı sunulmaktadır.' },
  ],
  faq: [
    { question: '2025\'te kredi sözleşmelerinde nelere dikkat etmeliyim?', answer: 'Kredi sözleşmelerinde özellikle faiz oranı, masraflar ve erken ödeme şartlarını kontrol edin. Bankaların bu bilgileri açıkça belirtme yükümlülüğü vardır.' },
    { question: 'Bankaların ücret artırımı yapma hakkı var mı?', answer: 'Evet, ancak 2025 yılı yasal düzenlemelerine göre bankalar ücret artırımlarını en az 30 gün önceden yazılı olarak bildirmek zorundadır.' },
  ],
  related: [],
}
