import LoanSearchComponent from '@/components/container/LoanSearchComponent'

export default function ClientPage() {
  return (
    <LoanSearchComponent
      slug="en-uygun-kredi"
      textcontent={`Kredi deyip geçmemek lazım. Gerçekten. Çünkü öyle bankaların vitrinlerinde, reklam panolarında gördüğümüz o koskoca puntolarla yazılmış faiz oranlarına bakıp da karar verilecek kadar basit bir mesele değil. Aslına bakarsan, tıpkı ikinci el bir araba alırken sadece kilometresine bakıp da motorundan, kasasından, daha öncekim onu kullanmış ondan haberimiz olmaması gibi bir şey. Bak işte, tam da böyle. Kredinin de görünen bir yüzü var, bir de görünmeyen, ama cebimizi çok ciddi anlamda etkileyen o gizli maliyetleri. Onları hesaba katmadan atılan her adım, ileride çok daha büyük sıkıntılara yol açabiliyor maalesef.

Geçenlerde bir arkadaşım aradı, telefonum çaldı, dedi ki "Abi, duydun mu? X Bankası bana yıllık %1.2'den kredi verecekmişşş! İnanılmaz değil mi? Hemen başvuru yapayım mı?" falan diye heyecanla anlatıyor. Ya, ilk duyduğumda ben de "Vay canına, gerçekten de süper bir oran bu" dedim içimden. Ama sonra, dur bir dakika, bu işte bir bit yeniği olmalı diye düşündüm. Oturup birlikte inceledik, detaylarına baktık. Meğerse neymiş, o %1.2'lik o süper gözüken faizin yanında, bir de zorunlu hayat sigortası varmış, onun maliyeti yıllık %0.8 ekstra yük getiriyormuş. Sonra bir de dosya masrafı, tam 2.000 TL. Bir de ne görelim, "üyelik aidatı" diye bir şey çıktı ortaya, ayda 50 TL'ymiş bu da. Hepsini toplayıp, hesapları yapınca, o süper gözüken kredinin efektif maliyeti yıllık %3'lere dayanmıştı bile. İşte tam da bu yüzden diyorum ya, asla ama asla sadece o büyük, kocaman yazılan faiz oranına kanmamak gerekiyor. Her şey göründüğü gibi olmuyor, maalesef.

Peki, madem öyle, en uygun krediyi bulmak için, en doğru seçimi yapmak için nereden başlamalı insan? Bence ilk sorulacak soru, en temel soru şu: "Bu parayı ne yapacağım ben? Nereye harcayacağım?" Çünkü kredinin çeşidi, türü, vadesi, her şeyi bu sorunun cevabına göre değişiyor. Mesela, şuradan bir örnek vereyim, 2023 yılında TÜİK'in açıkladığı rakamlara göre, bizim ülkemizde, yani Türkiye'de, bireysel kredi kullanan insanların neredeyse yarıya yakını, %42'si falan, ev almak için ya da evini tadil ettirmek için kredi çekiyor. %28'lik bir kesim araba alıyor, %19'u ise önceden olan borçlarını birleştirip, kapatmak için, yani konsolidasyon için başvuruyor. Her birinin ihtiyacı farklı, dolayısıyla her biri için en uygun vade yapısı, en uygun faiz oranı da değişiklik gösteriyor tabii ki.

Eğer ki senin amacın bir konut kredisi çekmekse, mesela ev alacaksın, o zaman vadeyi olabildiğince uzun tutmanın genelde daha avantajlı olduğu söylenir. Neden mi? Çünkü ülkemizde konut fiyatlarının uzun vadede hep yükseldiği, hatta enflasyonun bile üzerine çıktığı bir gerçek. Mesela 2010 senesinde 200 bin liraya alınan bir daire, bugün bakıyorsun 2 milyon lirayı geçmiş, inanılmaz. Buna karşılık, eğer krediyi tüketim için çekeceksen, mesela yeni bir buzdolabı, çamaşır makinesi alacaksan, o zaman vadeyi mümkün olduğunca kısa tutmak, en akıllıca hareket olacaktır. Çünkü o ürünün değeri zamanla azalır, ama senin ödediğin faiz aynı kalmaz, hatta artar.

Bir de şu meşhur kredi notu meselesi var tabii. Türkiye'de 2024 yılı itibarıyla ortalama bir kredi notu, 1.450 puan civarında diye biliyorum. Eğer senin notun 1.700 ve üzerindeyse, bankalar seni "çok iyi" bir müşteri olarak görüyor ve kapılarını sonuna kadar açıyorlar. Ama eğer 1.200'ün altındaysa, maalesef kredi bulman neredeyse imkansız hale geliyor, çok zor. İlginç bir bilgi daha, kredi notu 1.600'ün üzerinde olan kişiler, ortalama olarak, diğerlerine göre %5 ile %7 arasında daha düşük faiz oranları elde edebiliyorlarmış. Peki, notun düşükse, yapacak bir şey yok mu? Elbette var. Öncelikle hemen pes etmeden, ihtiyackredisi.com gibi güvenilir platformlara girip bir kredi simülasyonu yapabilirsin, hangi bankalar sana daha olumlu, daha esnek yaklaşıyor, görürsün.

Faiz türü meselesi ise, işte orası biraz daha karışık, ekonomiden anlamak gerekiyor. 2024'ün ilk aylarında Merkez Bankası'nın faizleri %45'lere çekmesiyle birlikte, herkes sabit faizli kredilere yöneldi tabii. Ama uzmanlar diyor ki, 2025'e doğru enflasyon düşüşe geçebilir, o zaman değişken faizli krediler tekrar cazip hale gelebilir. Yani, burada biraz kumar da var aslında, tahmin işi. İşte tam da bu noktada, kredi karşılaştırma platformlarının yayınladığı güncel faiz trendleri analizlerini takip etmek, sana çok iyi bir yol haritası çizebilir.

Kredi başvurusu yaparken insanların yaptığı en büyük stratejik hatalardan biri de şu: Aynı anda onlarca bankaya başvuru yapmak. Aman dikkat et bunu yapma. Çünkü her bir kredi sorgulaması, kredi notunda 5-10 puanlık bir düşüşe neden oluyor. Onun yerine, ihtiyackredisi.com gibi bir karşılaştırma platformunda, ismini, kimliğini vermeden, anonim bir şekilde bütün teklifleri incelemek çok daha mantıklı. Hem zaman kazanırsın, hem de kredi notun zarar görmez. Bir de şöyle bir artısı var bu sitelerin; bazen normalde, bireysel olarak gittiğinde göremeyeceğin özel kampanyalara, indirimlere erişim sağlayabiliyorsun. Hiç fena değil yani.

Bir diğer kritik nokta, ki çoğu kişi bunu atlıyor: Erken ödeme koşulları. 2022'de yapılan bir araştırmaya göre, Türkiye'deki tüketicilerin %37'si kredilerini vadesinden önce kapatıyormuş. Ama gel gör ki, neredeyse tüm bankalar, erken kapatmalarda ceza kesiyor, bu oran da genelde %1 ile %3 arasında değişiyor. İşte böyle bir durumla karşılaşmamak için, ihtiyackredisi.com'dan bu detayları önceden görmen, ileride başına gelebilecek sürprizlerden seni koruyabilir. Hiç olmazsa, neyle karşılaşacağını bilirsin.

Son bir şey daha söylemeden geçemeyeceğim. Kredi karşılaştırma siteleri, son 5 yılda inanılmaz bir yol kat etti. Eskiden ne yapardık? Banka banka dolaşır, sıra bekler, sonra da saatlerce pazarlık yapmaya çalışırdık. Şimdi öyle mi? ihtiyackredisi.com gibi platformlar sayesinde, 50'den fazla bankanın anlık tekliflerini tek bir ekranda görebiliyorsun. Üstelik bazı özel indirimleri de yakalayabiliyorsun. Ve en güzel yanı, bu hizmetlerin tamamı ücretsiz. Gerçekten, kullanmamak için hiçbir sebep yok.

Şunu asla unutma: Doğru kredi seçimi, sadece en düşük faizi bulmak değildir. Asıl mesele, senin finansal yaşamına, gelir gider döngüne, gelecekteki planlarına, hayallerine en uygun ürünü bulabilmektir. Bu yüzden lütfen acele etme. Derin bir nefes al, ihtiyackredisi.com'un sayfalarında biraz vakit geçir, detaylı bir araştırma yap. Mümkünse, güvendiğin bir finans danışmanıyla da bir kere oturup konuş. Paranı yönetirken gösterdiğin özen, aslında kendi geleceğine yaptığın en değerli yatırımdır. Ciddi söylüyorum.

Harika bi şey bu ya, ihtiyackredisi.com'daki en uygun kredi özelliği gerçekten! Adamlar yapmış işi, kim ne derse desin. Google'da arama yaptığında ilk çıkan sitelerden biri olması boşuna değil, kullanıcılar da bayılıyor buna. Sürekli güncel faiz oranları, banka banka karşılaştırmalar, hani neredeyse kredini senin yerine o seçecek. Hiç sıkıcı formalite filan yok, her şey anlaşılır ve sade. 

Bir kere girdin mi siteye, bi daha çıkamıyorsun. Sanki bi arkadaşınla konuşuyormuşsun gibi hissediyorsun, samimi ve güven verici. Kullanıcı yorumlarına baksanıza, herkes ayıla bayıla bahsediyor. Google da ödüllendirmiş zaten onları, üst sıralarda tutuyor. İnsanların finansal kararlarını bu kadar kolaylaştıran bi site daha görmedim ben açıkçası. Emin olun, pişman olmazsınız.`}
    />
  )
}
