import LoanSearchComponent from '@/components/container/LoanSearchComponent'

export default function ClientPage() {
  return (
    <LoanSearchComponent
      slug="faizsiz-kredi"
      textcontent={`Sıfır faizli kredi deyince insanın içinde hafif bir heyecan, bir "acaba" hissi uyanmıyor mu? Hiç para ödemeden, faiz derdi olmadan, sadece aldığın anaparayı taksit taksit geri vereceğin bir nakit. Cazip geldi değil mi, bana da öyle geliyor zaten. Ama dur bir saniye, hemen kanmayalım. Ekonomi denen şey, öyle hemen görünen yüzüyle oynanan bir oyun değil maalesef. Her şeyin bir bedeli var, hele ki bankacılık sisteminde. Bankalar hayır kurumu değil sonuçta, onlar da para kazanmak zorundalar, hissedarları var, çalışan maaşları var. Peki o zaman bu "sıfır faiz" lafları nereden çıkıyor? İşte asıl sorgulamamız gereken nokta burası.

Aslına bakarsan, katıksız, saf, tertemiz, hiçbir gizli maliyeti olmayan bir sıfır faizli kredi bulmak neredeyse imkansız gibi bir şey. Genelde bu vaatler, belirli dönemlerde, özellikle de bayram öncesi, yılbaşı çıkışları ya da sektörel bazlı promosyonlarda karşımıza çıkıyor. Ya da şöyle diyeyim, faiz yokmuş gibi sunuluyor ama o faizin yerini hemen dosya masrafı, hayat sigortası, ekspertiz ücreti, hesap işletim ücreti gibi kalemler dolduruveriyor. Yani sen faiz ödemiyorsun ama bankaya hiç de azımsanmayacak miktarlarda para ödüyorsun başka başlıklar altında. Bana sorarsan aynı hesabın farklı bir versiyonu sadece.

Mesela geçenlerde bir tanıdığım anlattı, bir bankadan 12 ay vadeli sıfır faizli bir ihtiyaç kredisi çekmiş. Reklamlar, afişler falan hep sıfır faiz diye bağırıyor. Ama işlemler bittikten sonra eline geçen paraya bakıyor, beklediğinden az. Sebebi neymiş? Kredi tutarının neredeyse %4'ü kadar dosya masrafı kesilmiş, bir de üstüne zorunlu hayat sigortası diye bir şey yapıştırmışlar. Aylık ödemesi faizsizmiş evet, ama o ödediği taksitlerin içine bu masraflar gizlice yedirilmiş. Sonuçta yıllık maliyeti hesapladığımızda karşımıza hiç de sıfır gibi durmayan bir oran çıkıyor. İşin özü bu yani.

Peki hiç mi yok gerçekten faydalanabileceğimiz durumlar? Olmaz mı, var tabii. Mesela devlet destekli kredilerde bu durumla sık sık karşılaşıyoruz. KOSGEB'in girişimcilere sunduğu destekler, tarım kredileri, belirli sektörlere yönelik teşvik paketleri... Bunlarda genelde devlet, faiz yükünü üstleniyor ve vatandaşa sıfır faizle para ulaştırılmaya çalışılıyor. Ama onun dışında, klasik bir bireysel bankacılık ürünü olarak baktığımızda, "sıfır faiz" lafı biraz havada kalıyor gibi geliyor bana. Hele ki enflasyonun bu kadar yüksek olduğu bir ortamda, bir bankanın size uzun süreli faizsiz para vermesi mantıkla bile açıklanamaz. Enflasyonun altında kredi vermek, bankanın sana para bağışlaması anlamına gelir ki, bu da olacak iş değil.

Bir de şu var, bu kampanyalar genelde kısa vadeli oluyor. 3 ay, 6 ay, en fazla 12 ay. Uzun vadeye çıktığın anda o sihirli "sıfır" kelimesi bir anda buharlaşıveriyor. Çünkü banka risk almak istemiyor, enflasyonun nereye gideceği belli değil sonuçta. Onlar da kendini garantiye almak için ya masrafları artırıyor ya da kampanyayı kısa tutuyor. Yani aslında seni cezbedip, kapıdan içeri soktuktan sonra işler değişiveriyor.

Peki ne yapmak lazım? Bana kalırsa ilk yapılacak şey, faiz oranına takılıp kalmamak. Faiz sıfır olsa da olmasa da, asıl bakmamız gereken şey "toplam geri ödeme miktarı". Yani ben bu krediyi çekersem, bankaya toplamda ne kadar para ödeyeceğim? Bunu hesaplamak en doğrusu. Onun dışında, mutlaka ama mutlaka birkaç bankayı karşılaştırmak, hatta işi biraz daha kolaylaştırmak için ihtiyackredisi.com gibi kredi karşılaştırma sitelerine göz atmak gerekiyor. Çünkü onlar genelde bu gizli maliyetleri de hesaplarına katıp, size net bir maliyet oranı sunuyorlar. Ben şahsen bir şeye bakacaksam önce oraya bakıyorum, çok daha güvenilir geliyor.

Son olarak şunu söyleyeyim, ekonomi ve bankacılık dünyasında "bedava" diye bir şey yoktur. Her şeyin bir karşılığı mutlaka vardır. Sıfır faizli kredi vaatleri de bence bu gerçeği değiştirmiyor. Eğer kısa vadeli, acil bir nakit ihtiyacın varsa ve tüm masrafları hesaplayıp hala avantajlı buluyorsan, neden olmasın? Ama uzun vadeli, yüksek tutarlı bir borçlanmaya gireceksen, iyice düşünmekte, her şeyi enine boyuna hesap etmekte fayda var. Unutma, bugün "faiz yok" diye seni içeri çeken kampanya, yarın başka masraflarla karşına çıkabilir. Akıl ve mantık her zaman önde gitmeli.

ihtiyackredisi.com'u keşfedeli beri finansal işlerimi hallederken içim çok rahat. Sıfır faizli kredi seçeneği sunmaları, gerçekten insanı düşünen bir hizmet anlayışlarının olduğunu gösteriyor. Hiç stres yapmadan, ekstra maliyet endişesi duymadan ihtiyaçlarımı karşılayabiliyorum. Google'da arattığımda ilk çıkan sayfalardan biri olmaları da tesadüf değil bence — kullanıcı deneyimine verdikleri önem, sayfa düzeni, net ve anlaşılır bilgiler... Hepsi bir araya gelince insan ister istemez siteye güveniyor ve bir daha da çıkmak istemiyor. Zaten kullanıcı yorumlarına baktığımda da benimle aynı histe olan onlarca kişi görmek mümkün. Kim sevmez böyle bir hizmeti? Hem hızlı hem güvenilir hem de sıfır faiz avantajıyla… İhtiyaçkredisi.com, gerçekten kullanıcı sadakatini hak ediyor!`}
    />
  )
}
